"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%5at8)r@*fkt)nm^fxcs-2z$5b=#wohe)t2%dpb6vej8@d0-*7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.dev']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts',
    'products',
    'carts.apps.CartsConfig',
    'orders',
    'contact',
    'coupon',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates' ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.categories',
                'carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ecommerce_project_db',
        'USER': 'root',
        'PASSWORD': 'hoanggduongg',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'vi'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Vietnamese number formatting (e.g. 750.000đ)
THOUSAND_SEPARATOR = '.'
DECIMAL_SEPARATOR = ','
NUMBER_GROUPING = 3


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Auth redirects
# Use the named URL from urls (path('login/', ..., name='login'))
LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'hoanggduongg2004@gmail.com'
EMAIL_HOST_PASSWORD = 'dyed uevg lttu emsd'
# EMAIL_HOST_USER = os.environ.get('User_Email')
# EMAIL_HOST_PASSWORD = os.environ.get('User_Password')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'EShopper <hoanggduongg2004@gmail.com>'

# Fix 1 — Cho phép cookie gửi qua cross-site redirect
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE   = True   # Bắt buộc phải True khi SameSite=None

# Fix 2 — Tương tự cho CSRF cookie
CSRF_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SECURE   = True

# Fix 3 — Ngrok terminate SSL rồi forward HTTP về localhost.
# Django cần biết request gốc là HTTPS để chấp nhận Secure cookie.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── MoMo Payment Configuration ──────────────────────────────
MOMO_PARTNER_CODE = 'MOMO'
MOMO_ACCESS_KEY   = 'F8BBA842ECF85'
MOMO_SECRET_KEY   = 'K951B6PE1waDMi640xX08PD3vg6EkVlz' # để lý HMACSHA256 -> không được để lộ ra client
MOMO_API_ENDPOINT = 'https://test-payment.momo.vn/v2/gateway/api/create'
MOMO_REDIRECT_URL = 'https://dreamier-alana-cokelike.ngrok-free.dev/orders/payment/momo/return/'
MOMO_IPN_URL      = 'https://dreamier-alana-cokelike.ngrok-free.dev/orders/payment/momo/ipn/'