# Generated by Django 5.2.11 on 2026-03-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_payment_remove_orderitem_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='momo_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
