# Generated by Django 5.2.11 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_coupon_order_discount_amount_order_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_shipping',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
