# Generated by Django 5.2.11 on 2026-03-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_discount_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_shipping',
            new_name='shipping_saved',
        ),
    ]
