# Generated by Django 5.2.11 on 2026-02-24 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_variation_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='Variation_category',
            new_name='variation_category',
        ),
    ]
