# Generated by Django 5.2.11 on 2026-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_updated_at_productvariant_price_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='products.variation'),
        ),
    ]
