# Generated by Django 5.2.11 on 2026-03-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productvariant_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variations',
            field=models.ManyToManyField(related_name='product_variants', to='products.variation'),
        ),
    ]
