# Generated by Django 5.2.11 on 2026-03-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='variations',
            field=models.ManyToManyField(blank=True, related_name='product_variants', to='products.variation'),
        ),
    ]
