# Generated by Django 5.2.11 on 2026-03-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productvariant_variations'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='color_image',
            field=models.ImageField(blank=True, help_text='Ảnh hiển thị (Render ra UI)', null=True, upload_to='variations/colors/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='label',
            field=models.CharField(blank=True, help_text='Tên hiển thị (VD: Wash, Denim)', max_length=100, null=True),
        ),
    ]
