# Generated by Django 5.2.11 on 2026-03-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productgallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productgallery',
            name='is_main',
        ),
    ]
