# Generated by Django 5.2.11 on 2026-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_productgallery_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgallery',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
